context: {}

package:
  name: r-rstan
  version: 2.32.6

source:
- url: https://cran.r-project.org/src/contrib/rstan_2.32.6.tar.gz
  md5: 93aecb7454d73942e9b0c719b2723505

build:
  script: 
    content: |
      # add -DHAVE_WORKING_LOG1P to PKG_CPPFLAGS
      sed -i '/^PKG_CPPFLAGS/a PKG_CPPFLAGS += "-DHAVE_WORKING_LOG1P"' src/Makevars

      R CMD INSTALL --build . ${R_ARGS}

requirements:
  build:
  - ${{ compiler('c') }}
  - ${{ compiler('cxx') }}
  - make
  - sed
  host:
  - r-base >=3.4.0
  - r-rcpp >=1.0.7
  - r-rcppeigen >=0.3.4.0.0
  - r-bh >=1.75.0-0
  - r-stanheaders >=2.32.0
  - r-rcppparallel >=5.1.4
  - r-inline >=0.3.19
  - r-gridextra >=2.3
  - r-loo >=2.4.1
  - r-pkgbuild >=1.2.0
  - r-quickjsr
  - r-ggplot2 >=3.3.5
  run:
  - r-inline >=0.3.19
  - r-gridextra >=2.3
  - r-rcpp >=1.0.7
  - r-rcppparallel >=5.1.4
  - r-loo >=2.4.1
  - r-pkgbuild >=1.2.0
  - r-quickjsr
  - r-ggplot2 >=3.3.5
  - r-stanheaders >=2.32.0
  # -  r-testthat >=3.0.4  # suggested
  # -  r-parallel  # suggested
  # -  r-kernsmooth  # suggested
  # -  r-shinystan  # suggested
  # -  r-bayesplot  # suggested
  # -  r-rmarkdown  # suggested
  # -  r-rstantools  # suggested
  # -  r-rstudioapi  # suggested
  # -  r-matrix  # suggested
  # -  r-knitr  # suggested
  # -  r-coda  # suggested
  # -  r-v8  # suggested

about:
  homepage: https://mc-stan.org/rstan/, https://discourse.mc-stan.org
  summary: R Interface to Stan
  description: |-
    User-facing R functions are provided to parse, compile,
    test, estimate, and analyze Stan models by accessing the
    header-only Stan library provided by the 'StanHeaders' package.
    The Stan project develops a probabilistic programming language
    that implements full Bayesian statistical inference via Markov
    Chain Monte Carlo, rough Bayesian inference via 'variational'
    approximation, and (optionally penalized) maximum likelihood
    estimation via optimization. In all three cases, automatic
    differentiation is used to quickly and accurately evaluate
    gradients without burdening the user with the need to derive
    the partial derivatives.
  license: GPL-3.0-or-later
  repository: https://github.com/cran/rstan

