[project]
name = "r-forge"
version = "0.1.0"
description = "Add a short description here"
authors = ["Wolf Vollprecht <w.vollprecht@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]
generate = "../rattler-build/target/debug/rattler-build generate-recipe cran -w "
build = "../rattler-build/target/debug/rattler-build build -m ./variant_config.yaml --recipe "

[dependencies]
rattler-build = ">=0.18.0,<0.19"
