context: {}

package:
  name: r-rcpp
  version: 1.0.12

source:
- url: https://cran.r-project.org/src/contrib/Rcpp_1.0.12.tar.gz
  sha256: 0c7359cc43beee02761aa3df2baccede1182d29d28c9cd49964b609305062bd0

build:
  script: R CMD INSTALL --build .

requirements:
  build:
  - ${{ compiler('c') }}
  - ${{ compiler('cxx') }}
  - make
  host:
  - r-base
  run:
  - r-base
  # -  r-tinytest  # suggested
  # -  r-inline  # suggested
  # -  r-rbenchmark  # suggested
  # -  r-pkgkitten >=0.1.2  # suggested

tests:
- script:
  - Rscript -e 'library("Rcpp")'

about:
  homepage: |-
    https://www.rcpp.org,
    https://dirk.eddelbuettel.com/code/rcpp.html,
    https://github.com/RcppCore/Rcpp
  summary: Seamless R and C++ Integration
  description: |-
    The 'Rcpp' package provides R functions as well as C++
    classes which offer a seamless integration of R and C++. Many R
    data types and objects can be mapped back and forth to C++
    equivalents which facilitates both writing of new code as well
    as easier integration of third-party libraries. Documentation
    about 'Rcpp' is provided by several vignettes included in this
    package, via the 'Rcpp Gallery' site at
    <https://gallery.rcpp.org>, the paper by Eddelbuettel and
    Francois (2011, <doi:10.18637/jss.v040.i08>), the book by
    Eddelbuettel (2013, <doi:10.1007/978-1-4614-6868-4>) and the
    paper by Eddelbuettel and Balamuta (2018,
    <doi:10.1080/00031305.2017.1375990>); see 'citation("Rcpp")'
    for details.
  license: GPL-2.0-or-later
  repository: https://github.com/cran/Rcpp

