context: {}

package:
  name: r-stanheaders
  version: 2.32.9

source:
- url: https://cran.r-project.org/src/contrib/StanHeaders_2.32.9.tar.gz
  md5: 9adcdeee94a569323f4643e66dda92b0

build:
  script: R CMD INSTALL --build .
  python: {}

requirements:
  build:
  - ${{ compiler('c') }}
  - ${{ compiler('cxx') }}
  - make
  host:
  - r-base >=3.4.0
  - r-rcppeigen >=0.3.4.0.0
  - r-rcppparallel >=5.1.4
  run:
  - r-rcppparallel >=5.1.4
  # -  r-rcpp  # suggested
  # -  r-bh >=1.75.0-0  # suggested
  # -  r-knitr >=1.36  # suggested
  # -  r-rmarkdown  # suggested
  # -  r-matrix  # suggested
  # -  r-methods  # suggested
  # -  r-rstan  # suggested
  # -  r-withr  # suggested

about:
  homepage: https://mc-stan.org/
  summary: C++ Header Files for Stan
  description: |-
    The C++ header files of the Stan project are provided by
    this package, but it contains little R code or documentation.
    The main reference is the vignette. There is a shared object
    containing part of the 'CVODES' library, but its functionality
    is not accessible from R. 'StanHeaders' is primarily useful for
    developers who want to utilize the 'LinkingTo' directive of
    their package's DESCRIPTION file to build on the Stan library
    without incurring unnecessary dependencies. The Stan project
    develops a probabilistic programming language that implements
    full or approximate Bayesian statistical inference via Markov
    Chain Monte Carlo or 'variational' methods and implements
    (optionally penalized) maximum likelihood estimation via
    optimization. The Stan library includes an advanced automatic
    differentiation scheme, 'templated' statistical and linear
    algebra functions that can handle the automatically
    'differentiable' scalar types (and doubles, 'ints', etc.), and
    a parser for the Stan language. The 'rstan' package provides
    user-facing R functions to parse, compile, test, estimate, and
    analyze Stan models.
  license: BSD-3-Clause
  license_file: LICENSE
  repository: https://github.com/cran/StanHeaders

