context: {}

package:
  name: r-highr
  version: '0.11'

source:
- url: https://cran.r-project.org/src/contrib/highr_0.11.tar.gz
  sha256: e90d14284001963325a84a9dbeef029609d52515da8d65c87ae61be21b7fe0a7

build:
  script: R CMD INSTALL --build .

requirements:
  host:
  - r-base
  - r-base >=3.3.0
  - r-xfun >=0.18
  run:
  - r-base
  - r-xfun >=0.18
  # -  r-knitr  # suggested
  # -  r-markdown  # suggested
  # -  r-testit  # suggested

tests:
- script:
  - Rscript -e 'library("highr")'

about:
  homepage: https://github.com/yihui/highr
  summary: Syntax Highlighting for R Source Code
  description: |-
    Provides syntax highlighting for R source code. Currently
    it supports LaTeX and HTML output. Source code of other
    languages is supported via Andre Simon's highlight package
    (<https://gitlab.com/saalen/highlight>).
  license: GPL-2.0
  repository: https://github.com/cran/highr

